In [27]:
import torch
import torch.nn as nn
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])


In [28]:
# softmax
output = torch.softmax(x, dim=0) # standalone function used outside the model
print(output)
sm = nn.Softmax(dim=0)# module that can be included in a neural network model
output = sm(x)
print(output)
total = torch.sum(output)
print(total)

tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor(1.)


In [29]:
# sigmoid 
output = torch.sigmoid(x)
print(output)
s = nn.Sigmoid()
output = s(x)
print(output)


tensor([0.2689, 0.7311, 0.8808, 0.9526])
tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [30]:
#tanh
output = torch.tanh(x)
print(output)
t = nn.Tanh()
output = t(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])
tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [31]:
output = torch.relu(x)
print(output)
relu = nn.ReLU()
output = relu(x)
print(output)

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


In [32]:
# option 1 (create nn modules)

import torch
import torch.nn as nn

class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out
    
input_size = 10
hidden_size = 20
net = NeuralNet(input_size, hidden_size)
input_tensor = torch.randn(1, input_size)
print(input_tensor)
output_tensor = net.forward(input_tensor)
print(output_tensor)

tensor([[-0.3201, -0.2711, -0.1646,  1.0943, -1.0064, -0.8087,  0.2133, -0.4451,
          0.4423, -0.3985]])
tensor([[0.4895]], grad_fn=<SigmoidBackward0>)


In [33]:
# option 2 (use activation functions directly in forward pass)
import torch
import torch.nn as nn

class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out
    
input_size = 10
hidden_size = 20
net = NeuralNet(input_size, hidden_size)

# Convert the list to a Tensor
input_tensor = torch.randn(1, input_size)
print(input_tensor)
output_tensor = net.forward(input_tensor)
print(output_tensor)


tensor([[-1.0545,  0.0213,  0.8131,  2.0637,  1.7618,  0.6647,  0.0624,  0.2204,
         -1.7223, -0.0438]])
tensor([[0.4706]], grad_fn=<SigmoidBackward0>)
