In [1]:
import torch

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[1.0267e-08, 1.0244e-11, 1.3237e+22],
        [1.0503e-05, 3.3703e-06, 2.5812e-06]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[9.9184e-39, 9.0000e-39, 1.0561e-38],
          [1.0653e-38, 4.1327e-39, 8.9082e-39]],

         [[9.8265e-39, 9.4592e-39, 1.0561e-38],
          [1.0653e-38, 1.0469e-38, 9.5510e-39]]],


        [[[8.7245e-39, 9.6429e-39, 1.0286e-38],
          [1.0653e-38, 9.5510e-39, 8.7245e-39]],

         [[9.6429e-39, 9.6429e-39, 8.7245e-39],
          [4.2246e-39, 1.1112e-38, 1.4013e-43]]]])


In [7]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.1664, 0.5345, 0.2196],
        [0.6330, 0.6956, 0.9788],
        [0.3007, 0.3985, 0.7791],
        [0.0957, 0.6831, 0.8018],
        [0.7177, 0.2977, 0.0433]])


In [8]:
# torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# check size
print(x.size())

torch.Size([5, 3])


In [10]:
# check data type
print(x.dtype)

torch.float32


In [11]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [12]:
# check type
print(x.dtype)

torch.float16


In [13]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [14]:
# requires_grad argument
x = torch.tensor([5.5, 3], requires_grad=True)
print (x)

tensor([5.5000, 3.0000], requires_grad=True)


In [15]:
# Define tensors
x = torch.tensor([5.5, 3], requires_grad=True)  # Tensor with gradient tracking
y = torch.tensor([5.5, 3], requires_grad=False) # Tensor without gradient tracking

# Perform an operation
z = x.sum() + y.sum()
print("Value of z:", z.item())

# Backward pass to compute gradients
z.backward()

# Print gradients
print("Gradient for x (requires_grad=True):", x.grad)
print("Gradient for y (requires_grad=False):", y.grad)

Value of z: 17.0
Gradient for x (requires_grad=True): tensor([1., 1.])
Gradient for y (requires_grad=False): None


In [16]:
# Operations on Tensors
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
# elementwise addition
z = x + y
# torch.add(x,y) 
print (z)

tensor([[0.0738, 0.9370],
        [0.2457, 0.6483]])
tensor([[0.2270, 0.9069],
        [0.4537, 0.1733]])
tensor([[0.3008, 1.8439],
        [0.6994, 0.8216]])


In [17]:
# subtraction
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x - y
z = torch.sub(x, y)
print (z)

tensor([[0.2273, 0.9678],
        [0.3143, 0.0087]])
tensor([[0.1588, 0.5192],
        [0.6675, 0.0072]])
tensor([[ 0.0685,  0.4486],
        [-0.3532,  0.0015]])


In [18]:
# multiplication
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x * y
z = torch.mul(x,y)
print (z)


tensor([[0.1401, 0.9909],
        [0.5694, 0.2946]])
tensor([[0.6139, 0.9956],
        [0.3378, 0.8887]])
tensor([[0.0860, 0.9866],
        [0.1923, 0.2618]])


In [19]:
# division
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z1 = x / y
z1 = torch.div(x,y)
print(z1)

tensor([[0.8876, 0.9513],
        [0.2812, 0.7553]])
tensor([[0.7502, 0.8675],
        [0.9369, 0.9957]])
tensor([[1.1832, 1.0966],
        [0.3002, 0.7586]])


In [20]:
#Slicing
x = torch.rand(5,3)
print("Slicing")
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

Slicing
tensor([[0.4165, 0.1840, 0.2761],
        [0.3558, 0.9625, 0.7244],
        [0.4170, 0.1676, 0.4285],
        [0.0251, 0.6685, 0.8838],
        [0.7731, 0.6377, 0.5933]])
tensor([0.4165, 0.3558, 0.4170, 0.0251, 0.7731])
tensor([0.3558, 0.9625, 0.7244])
tensor(0.9625)
0.962531566619873


In [21]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[-1.3773, -0.1995, -1.1930,  0.0548],
        [ 0.8647, -1.3404,  2.3077, -1.7224],
        [-0.2230,  0.3279, -1.7396, -1.5859],
        [-0.2461, -1.0504,  1.5725, -1.3133]])
tensor([-1.3773, -0.1995, -1.1930,  0.0548,  0.8647, -1.3404,  2.3077, -1.7224,
        -0.2230,  0.3279, -1.7396, -1.5859, -0.2461, -1.0504,  1.5725, -1.3133])
tensor([[-1.3773, -0.1995, -1.1930,  0.0548,  0.8647, -1.3404,  2.3077, -1.7224],
        [-0.2230,  0.3279, -1.7396, -1.5859, -0.2461, -1.0504,  1.5725, -1.3133]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
# Numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# If the Tensor is on the CPU, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
# Numpy to Torch
print("Numpy to Torch")
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


Numpy to Torch
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
#They also share same memory
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# The Autograd Package
print("Autograd Package")
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    print(model_output)
    
    model_output.backward()
    print(weights.grad)

    with torch.no_grad():
        weights -= 0.1 * weights.grad
        

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

Autograd Package
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(8.4000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(4.8000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
