In [2]:
import torch

In [3]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([1.6962e+19])


In [4]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([3.8750e-29, 4.0441e-41, 3.8750e-29])


In [5]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[4.0737e+05, 3.5544e-41, 4.0737e+05],
        [3.5544e-41, 1.1210e-43, 0.0000e+00]])


In [6]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)

tensor([[[1.0235e+08, 3.5544e-41, 1.0240e+08],
         [3.5544e-41, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 3.8750e-29, 4.0441e-41]]])


In [7]:
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[[ 3.8750e-29,  4.0441e-41,  1.6988e+08],
          [ 3.5544e-41,  4.1302e+05,  3.5544e-41]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  1.0234e+08,  3.5544e-41]]],


        [[[ 2.2343e+07,  3.5544e-41, -2.6042e+05],
          [ 4.0440e-41,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


In [8]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.3878, 0.0938, 0.8267],
        [0.1032, 0.8981, 0.9873],
        [0.5187, 0.6385, 0.2863],
        [0.7965, 0.3645, 0.9174],
        [0.7055, 0.7584, 0.3781]])


In [9]:
# torch.zeros(size), fill with 0
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# check size
print(x.size())

torch.Size([5, 3])


In [11]:
# check data type
print(x.dtype)

torch.float32


In [12]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [13]:
# check type
print(x.dtype)

torch.float16


In [14]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [15]:
# requires_grad argument
x = torch.tensor([5.5, 3], requires_grad=True)
print (x)

tensor([5.5000, 3.0000], requires_grad=True)


In [16]:
# Define tensors
x = torch.tensor([5.5, 3], requires_grad=True)  # Tensor with gradient tracking
y = torch.tensor([5.5, 3], requires_grad=False) # Tensor without gradient tracking

# Perform an operation
z = x.sum() + y.sum()
print("Value of z:", z.item())

# Backward pass to compute gradients
z.backward()

# Print gradients
print("Gradient for x (requires_grad=True):", x.grad)
print("Gradient for y (requires_grad=False):", y.grad)

Value of z: 17.0
Gradient for x (requires_grad=True): tensor([1., 1.])
Gradient for y (requires_grad=False): None


In [17]:
# Operations on Tensors
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
# elementwise addition
z = x + y
# torch.add(x,y) 
print (z)

tensor([[0.6743, 0.8453],
        [0.5836, 0.9152]])
tensor([[0.2426, 0.9725],
        [0.7362, 0.9908]])
tensor([[0.9169, 1.8178],
        [1.3198, 1.9060]])


In [18]:
# subtraction
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x - y
z = torch.sub(x, y)
print (z)

tensor([[0.3717, 0.7505],
        [0.0850, 0.1606]])
tensor([[0.3243, 0.3959],
        [0.3747, 0.5323]])
tensor([[ 0.0474,  0.3546],
        [-0.2897, -0.3718]])


In [19]:
# multiplication
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z = x * y
z = torch.mul(x,y)
print (z)


tensor([[0.1246, 0.9178],
        [0.5772, 0.4089]])
tensor([[0.8765, 0.2313],
        [0.0834, 0.6504]])
tensor([[0.1092, 0.2123],
        [0.0481, 0.2660]])


In [20]:
# division
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print (x)
print (y)
z1 = x / y
z1 = torch.div(x,y)
print(z1)

tensor([[0.9882, 0.3798],
        [0.8172, 0.3676]])
tensor([[0.3619, 0.1912],
        [0.8532, 0.4840]])
tensor([[2.7306, 1.9865],
        [0.9578, 0.7596]])


In [21]:
#Slicing
x = torch.rand(5,3)
print("Slicing")
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

Slicing
tensor([[0.4558, 0.2018, 0.4228],
        [0.1349, 0.0615, 0.2798],
        [0.3531, 0.2607, 0.5431],
        [0.4615, 0.3661, 0.1340],
        [0.6714, 0.1015, 0.1543]])
tensor([0.4558, 0.1349, 0.3531, 0.4615, 0.6714])
tensor([0.1349, 0.0615, 0.2798])
tensor(0.0615)
0.06145131587982178


In [22]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[-0.6619,  0.5882, -0.8814,  0.9515],
        [-0.4185,  0.1198, -0.6695, -0.0303],
        [-0.1350,  0.8704,  1.2312,  2.2873],
        [ 0.2247,  0.9839,  0.4947, -0.6605]])
tensor([-0.6619,  0.5882, -0.8814,  0.9515, -0.4185,  0.1198, -0.6695, -0.0303,
        -0.1350,  0.8704,  1.2312,  2.2873,  0.2247,  0.9839,  0.4947, -0.6605])
tensor([[-0.6619,  0.5882, -0.8814,  0.9515, -0.4185,  0.1198, -0.6695, -0.0303],
        [-0.1350,  0.8704,  1.2312,  2.2873,  0.2247,  0.9839,  0.4947, -0.6605]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# Numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

# If the Tensor is on the CPU, they will share the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
# Numpy to Torch
print("Numpy to Torch")
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)


Numpy to Torch
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
#They also share same memory
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
# The Autograd Package
print("Autograd Package")
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    print(model_output)
    
    model_output.backward()
    print(weights.grad)

    with torch.no_grad():
        weights -= 0.1 * weights.grad
        

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

Autograd Package
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(8.4000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(4.8000, grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)
